nightscout:
  image: dhermanns/rpi-nightscout:0.9.2
  environment:
    TZ: US/Eastern
    MONGO_CONNECTION: mongodb://mongo:27017/nightscout
    ENABLE: bridge openaps rawbg pump iob careportal cob cwg cage basal
    DEVICESTATUS_ADVANCED: true
    API_SECRET: nightscout2000
    BRIDGE_USER_NAME: USERNAME
    BRIDGE_PASSWORD: Passwrod
    BG_HIGH: 220
    BG_LOW: 60
    BG_TARGET_TOP: 180
    BG_TARGET_BOTTOM: 80
#    SSL_KEY: /var/opt/ssl/server.key
#    SSL_CERT: /var/opt/ssl/serverchain.crt
#    SSL_CA: /var/opt/ssl/cachain.crt
  ports:
    - "1337:1337"
  links:
    - mongo
  volumes:
    - /home/pi/docker/rpi-nightscout:/var/opt/ssl/:ro
  restart: always
mongo:
  image: dhermanns/rpi-mongo:2.6.4
  command: "/opt/mongodb/bin/mongod"
  restart: always
